### PR TITLE
Transition to new Constitution

### PR DESCRIPTION
**Pull request by chorman0773**

### CODE REVIEW

**Review by WahidBawa — APPROVED** [review]
I approve

**Review by jere-mie — APPROVED** [review]
I approve

**Review by JSabelli-FDX — COMMENTED** [review]
Approved.

**Review by JSabelli-FDX — APPROVED** [review]

**Review by Craiga214 — APPROVED** [review]
I approve.

**Review by chorman0773 — COMMENTED** [review]
On record, I approve.

**Review by pekcus — APPROVED** [review]

**Pull request merged**
